// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webcam_image_viewer;

#nullable disable

namespace webcam_image_viewer.Migrations
{
    [DbContext(typeof(WebcamDbContext))]
    [Migration("20240503174216_WebcamUserBase")]
    partial class WebcamUserBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webcam_image_viewer.Entities.GarageImage", b =>
                {
                    b.Property<int>("GarageImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBySub")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ImageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ModifiedBySub")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NumberOfCars")
                        .HasColumnType("int");

                    b.Property<string>("S3Key")
                        .HasColumnType("longtext");

                    b.HasKey("GarageImageId");

                    b.HasIndex("CreatedBySub");

                    b.HasIndex("ModifiedBySub");

                    b.ToTable("GarageImage");
                });

            modelBuilder.Entity("webcam_image_viewer.Entities.WebcamUser", b =>
                {
                    b.Property<Guid>("Sub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Sub");

                    b.ToTable("WebcamUser");
                });

            modelBuilder.Entity("webcam_image_viewer.Entities.GarageImage", b =>
                {
                    b.HasOne("webcam_image_viewer.Entities.WebcamUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedBySub");

                    b.HasOne("webcam_image_viewer.Entities.WebcamUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedBySub");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
