name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Version pr
      if: ${{ github.event_name == 'pull_request' }}
      id: version-pr
      uses: paulhatch/semantic-version@v4.0.2
      with:
        format: "${major}.${minor}.${patch}-${{ github.event.pull_request.head.ref }}"
        namespace: test

    - name: Version
      if: ${{ github.event_name == 'push' }}
      id: version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        format: "${major}.${minor}.${patch}"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image
      shell: bash
      run: ./build-scripts/docker.sh ${{ steps.version-pr.outputs.version }} ${{ steps.version-pr.outputs.version_tag }}