name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Version pr
      if: ${{ github.event_name == 'pull_request' }}
      id: version-pr
      uses: paulhatch/semantic-version@v4.0.2
      with:
        namespace: ${{ github.event.pull_request.head.ref }}

    - name: Version
      if: ${{ github.event_name == 'push' }}
      id: version
      uses: paulhatch/semantic-version@v4.0.3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push docker image
      shell: bash
      run: ./build-scripts/docker.sh $VERSION $VERSION_TAG
      env:
        VERSION: "${{ github.event_name == 'push' && steps.version.outputs.version || steps.version-pr.outputs.version }}"
        VERSION_TAG: "${{ github.event_name == 'push' && steps.version.outputs.version_tag || '' }}"