name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write  # Read required for actions/checkout; Write required pushing tag

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Version
      id: version
      uses: paulhatch/semantic-version@v5.3.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image
      id: build-image
      shell: bash
      run: ./build-scripts/docker.sh $VERSION $VERSION_TAG
      env:
        VERSION: "${{ github.event_name == 'push' && steps.version.outputs.version || format('{0}-prerelease.{1}', steps.version.outputs.version, steps.version.outputs.increment) }}"
        VERSION_TAG: "${{ github.event_name == 'push' && steps.version.outputs.version_tag || '' }}"

    - name: Configure AWS credentials
      if: ${{ github.event_name == 'push' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::515964707541:role/github-oidc-idp-role
        aws-region: us-east-2

    - name: Fill in the new image ID in the Amazon ECS task definition
      if: ${{ github.event_name == 'push' }}
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ github.workspace }}/.github/workflows/task-definition.json
        container-name: webcam-image-viewer
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      if: ${{ github.event_name == 'push' }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: webcam-image-viewer
        cluster: ProjectsProd
        wait-for-service-stability: true
        wait-for-minutes: 10
        force-new-deployment: true